# Generated by Django 4.0.3 on 2022-03-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_issue_status_book_issue_date_and_more'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='reminder',
        ),
        migrations.AddField(
            model_name='member',
            name='issue_history',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reserve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reserved_book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_id', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('penalty', models.FloatField(default=0.0)),
                ('date_of_rem', models.DateField(null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
