# Generated by Django 4.0.3 on 2022-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_reminder_member_issue_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='insti_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
