# Generated by Django 4.0.3 on 2022-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_insti_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='reserve_date',
        ),
        migrations.AddField(
            model_name='member',
            name='reserve_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
