# Generated by Django 4.0.3 on 2022-03-28 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_issue_status_book_issue_date_and_more'),
        ('member', '0004_remove_member_reserve_date_member_reserve_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
