# Generated by Django 4.0.3 on 2022-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_delete_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_of_rem',
            field=models.DateTimeField(null=True),
        ),
    ]
