# Generated by Django 4.0.3 on 2022-03-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_reminder_date_of_rem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='date_of_rem',
            new_name='rem_datetime',
        ),
    ]
