# Generated by Django 4.0.3 on 2022-03-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_return_requested'),
        ('member', '0008_rename_date_of_rem_reminder_rem_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('penalty', models.FloatField(default=0.0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
