# Generated by Django 4.0.3 on 2022-03-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_reminder_book'),
        ('member', '0009_issuethread'),
    ]

    operations = [
    ]
