# Generated by Django 3.2.12 on 2022-03-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_reminder_book'),
        ('member', '0009_issuethread'),
    ]

    operations = [
    ]
