# Generated by Django 3.2.12 on 2022-03-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_last_issued_date'),
        ('member', '0010_merge_0009_alter_reminder_book_0009_issuethread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuethread',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
