# Generated by Django 3.2.12 on 2022-03-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_issuethread_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='issue_history',
        ),
    ]
