# Generated by Django 4.0.3 on 2022-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=15)),
                ('rack_number', models.CharField(max_length=10)),
                ('issue_status', models.CharField(max_length=15)),
                ('date_issued', models.DateField(null=True)),
            ],
        ),
    ]
