# Generated by Django 4.0.3 on 2022-03-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('book', '0002_rename_date_issued_book_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='issue_status',
            new_name='issue_date',
        ),
        migrations.AddField(
            model_name='book',
            name='issue_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
    ]
