# Generated by Django 3.2.12 on 2022-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_return_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_issued_date',
            field=models.DateField(null=True),
        ),
    ]
